# Generated by Django 3.2.5 on 2022-03-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsPython',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question', models.CharField(max_length=1000)),
                ('answers', models.CharField(max_length=5000)),
                ('videos', models.FileField(blank=True, upload_to='phase2/')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_audio_text', models.CharField(max_length=5000)),
                ('illegal_face', models.IntegerField(blank=True, default=1)),
                ('illegal_eye', models.IntegerField(blank=True, default=1)),
                ('illegal_body', models.IntegerField(blank=True, default=1)),
                ('eye_blink_count', models.IntegerField(blank=True, default=1)),
                ('text_match', models.IntegerField(blank=True, default=1)),
            ],
        ),
    ]
