# Generated by Django 3.2.5 on 2022-03-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_phase', '0003_solutionbodyposture_solutioneyecontact_solutionface'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsCN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question', models.CharField(max_length=1000)),
                ('answers', models.CharField(max_length=5000)),
                ('videos', models.FileField(blank=True, upload_to='phase2_5/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsDBMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question', models.CharField(max_length=1000)),
                ('answers', models.CharField(max_length=5000)),
                ('videos', models.FileField(blank=True, upload_to='phase2_3/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question', models.CharField(max_length=1000)),
                ('answers', models.CharField(max_length=5000)),
                ('videos', models.FileField(blank=True, upload_to='phase2_2/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question', models.CharField(max_length=1000)),
                ('answers', models.CharField(max_length=5000)),
                ('videos', models.FileField(blank=True, upload_to='phase2_4/')),
            ],
        ),
    ]
