# Generated by Django 3.2.5 on 2022-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_phase', '0004_questionscn_questionsdbms_questionsds_questionsos'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='emotion_report',
            field=models.CharField(default=1, max_length=6000),
        ),
    ]
